<field:nydjzh itemname="农药登记证号" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:nydjzh>
<field:scpzzh itemname="生产批准证号" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:scpzzh>
<field:cpbzzh itemname="产品标准证号" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cpbzzh>
<field:chanpinguige itemname="产品规格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:chanpinguige>
<field:jixing itemname="剂型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jixing>
<field:jyzt itemname="检验状态" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:jyzt>
<field:shengchanleixing itemname="生产类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="登记证持有人生产"  maxlength="50" page="">
</field:shengchanleixing>
<field:duxing itemname="毒性" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="低毒"  maxlength="50" page="">
</field:duxing>
<field:hits itemname="产品防伪码" autofield="1" notsend="0" type="datetime" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hits>
<field:shengchanriqi itemname="生产日期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="见包装袋"  maxlength="30" page="">
</field:shengchanriqi>
<field:baozhiqi itemname="保质期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="2年"  maxlength="10" page="">
</field:baozhiqi>
<field:ziduan1 itemname="字段1" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:ziduan1>
<field:ziduan2 itemname="字段2" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:ziduan2>
<field:ziduan3 itemname="字段3" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:ziduan3>
<field:ziduan4 itemname="字段4" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:ziduan4>
<field:ziduan5 itemname="字段5" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:ziduan5>
<field:tuiguangfangxian itemname="推广方向" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tuiguangfangxian>
<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
