
<field:nydjzh itemname="农药登记证号" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:nydjzh>

<field:scpzzh itemname="生产批准证号" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:scpzzh>

<field:cpbzzh itemname="产品标准证号" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cpbzzh>

<field:chanpinguige itemname="产品规格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:chanpinguige>

<field:jixing itemname="剂型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jixing>

<field:jyzt itemname="检验状态" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:jyzt>

<field:shengchanleixing itemname="生产类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="登记证持有人生产"  maxlength="50" page="">
</field:shengchanleixing>

<field:duxing itemname="毒性" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="低毒"  maxlength="50" page="">
</field:duxing>

<field:hits itemname="产品防伪码" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hits>

<field:shengchanriqi itemname="生产日期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="见包装袋"  maxlength="30" page="">
</field:shengchanriqi>

<field:baozhiqi itemname="保质期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="2年"  maxlength="10" page="">
</field:baozhiqi>
