
<field:nydjzh itemname="农药登记证号" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:nydjzh>

<field:scpzzh itemname="生产批准证号" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:scpzzh>

<field:cpbzzh itemname="产品标准证号" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cpbzzh>

<field:chanpinguige itemname="产品规格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:chanpinguige>

<field:jixing itemname="剂型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jixing>
