<?php
$z[0]=Array("global","",91,118);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",170,197);
$z[1][4]=array();
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",283,310);
$z[2][4]=array();
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",386,413);
$z[3][4]=array();
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",525,552);
$z[4][4]=array();
$z[4][4]['name']="cfg_basehost";

?>