<?php
$z[0]=Array("include","",0,37);
$z[0][4]=array();
$z[0][4]['filename']="header.htm";
$z[1]=Array("global","",1094,1121);
$z[1][4]=array();
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1123,1150);
$z[2][4]=array();
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",1231,1258);
$z[3][4]=array();
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("include","",1383,1420);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>