<?php
$z[0]=Array("include","",0,37);
$z[0][4]=array();
$z[0][4]['filename']="header.htm";
$z[1]=Array("global","",1080,1107);
$z[1][4]=array();
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1109,1136);
$z[2][4]=array();
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("qrcode","",1298,1312);
$z[3][4]=array();
$z[4]=Array("include","",1349,1386);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>