<?php
$z[0]=Array("include","",0,37);
$z[0][4]=array();
$z[0][4]['filename']="header.htm";
$z[1]=Array("list","\r\n   <a href=\"[field:arcurl/]\" title=\"[field:title/]\" >\r\n  <li><span>></span>\r\n    <div class=\"pic_fl\"><img src=\"[field:litpic/]\" alt=\"\" width=\"60px\" height=\"60px\" /></div>\r\n    [field:title/]</li>\r\n  </a>\r\n   ",652,899);
$z[1][4]=array();
$z[1][4]['pagesize']="10";
$z[2]=Array("pagelist","",966,1013);
$z[2][4]=array();
$z[2][4]['listitem']="pageno";
$z[2][4]['listsize']="5";
$z[3]=Array("include","",1059,1096);
$z[3][4]=array();
$z[3][4]['filename']="footer.htm";

?>